import type { Theme, ThemeId } from './theme.types';

/**
 * The six launch themes from the PRD "100500 тем" table (§6). Each theme reskins
 * the mascot, collectible artifact, celebration visuals, the solo dream build,
 * and the full colour palette.
 */
export const THEMES: Record<ThemeId, Theme> = {
  unicorns: {
    id: 'unicorns',
    name: 'Єдинороги',
    icon: '🦄',
    mascot: { name: 'Чарівний Поні', emoji: '🦄' },
    goal: { name: 'Веселка', emoji: '🌈' },
    artifact: { name: 'Сяючий Кристал', emoji: '💎' },
    celebrationEmojis: ['🌈', '⭐', '✨', '💖', '🦄'],
    pathIcons: ['💎', '🌟', '🧁', '🍬', '🌸'],
    dreamBuild: { name: 'Замок Мрій', emoji: '🏰' },
    palette: {
      bg1: '#fdf2ff',
      bg2: '#ede9fe',
      surface: '#ffffff',
      surfaceInk: '#4c1d95',
      primary: '#a855f7',
      primaryInk: '#ffffff',
      accent: '#f472b6',
      accentInk: '#ffffff',
      text: '#3b0764',
      textSoft: '#7c6a99',
      ring: '#e879f9',
    },
  },
  cars: {
    id: 'cars',
    name: 'Тачки',
    icon: '🏎️',
    mascot: { name: 'Спорткар-Блискавка', emoji: '🏎️' },
    goal: { name: 'Фінішний прапор', emoji: '🏁' },
    artifact: { name: 'Золота Шестерня', emoji: '⚙️' },
    celebrationEmojis: ['🏁', '🏆', '⚙️', '🔥', '🏎️'],
    pathIcons: ['⚙️', '🛞', '🔧', '🏁', '🏆'],
    dreamBuild: { name: 'Гоночне Авто', emoji: '🏎️' },
    palette: {
      bg1: '#fff7ed',
      bg2: '#fee2e2',
      surface: '#ffffff',
      surfaceInk: '#7f1d1d',
      primary: '#ef4444',
      primaryInk: '#ffffff',
      accent: '#f59e0b',
      accentInk: '#1c1917',
      text: '#7c2d12',
      textSoft: '#9a6a4a',
      ring: '#fb923c',
    },
  },
  space: {
    id: 'space',
    name: 'Космос',
    icon: '🚀',
    mascot: { name: 'Робот-Астронавт', emoji: '🤖' },
    goal: { name: 'Планета', emoji: '🪐' },
    artifact: { name: 'Космічний Метеор', emoji: '☄️' },
    celebrationEmojis: ['⭐', '☄️', '🪐', '✨', '🚀'],
    pathIcons: ['⭐', '🪐', '☄️', '🌙', '🛸'],
    dreamBuild: { name: 'Ракета', emoji: '🚀' },
    palette: {
      bg1: '#0f172a',
      bg2: '#1e1b4b',
      surface: '#1e293b',
      surfaceInk: '#e0e7ff',
      primary: '#6366f1',
      primaryInk: '#ffffff',
      accent: '#22d3ee',
      accentInk: '#082f49',
      text: '#e2e8f0',
      textSoft: '#94a3b8',
      ring: '#818cf8',
    },
  },
  dinos: {
    id: 'dinos',
    name: 'Динозаври',
    icon: '🦖',
    mascot: { name: 'Динозаврик Рекс', emoji: '🦖' },
    goal: { name: 'Вулкан', emoji: '🌋' },
    artifact: { name: 'Стародавня Мушля', emoji: '🐚' },
    celebrationEmojis: ['🦖', '🌿', '🦕', '🥚', '🌋'],
    pathIcons: ['🥚', '🦴', '🌿', '🐚', '🌋'],
    dreamBuild: { name: 'Загублений Світ', emoji: '🏝️' },
    palette: {
      bg1: '#f0fdf4',
      bg2: '#dcfce7',
      surface: '#ffffff',
      surfaceInk: '#14532d',
      primary: '#16a34a',
      primaryInk: '#ffffff',
      accent: '#ca8a04',
      accentInk: '#ffffff',
      text: '#14532d',
      textSoft: '#4d7c5a',
      ring: '#4ade80',
    },
  },
  underwater: {
    id: 'underwater',
    name: 'Підводний світ',
    icon: '🌊',
    mascot: { name: 'Веселий Крабик', emoji: '🦀' },
    goal: { name: 'Скарб', emoji: '🏴‍☠️' },
    artifact: { name: 'Морська Перлина', emoji: '🫧' },
    celebrationEmojis: ['🫧', '🐠', '🐬', '⭐', '🐚'],
    pathIcons: ['🐚', '🐠', '🪸', '⭐', '🦀'],
    dreamBuild: { name: 'Підводний Човен', emoji: '🚢' },
    palette: {
      bg1: '#ecfeff',
      bg2: '#cffafe',
      surface: '#ffffff',
      surfaceInk: '#164e63',
      primary: '#0891b2',
      primaryInk: '#ffffff',
      accent: '#f59e0b',
      accentInk: '#1c1917',
      text: '#164e63',
      textSoft: '#4a8296',
      ring: '#22d3ee',
    },
  },
  forest: {
    id: 'forest',
    name: 'Лісова казка',
    icon: '🌿',
    mascot: { name: 'Мудре Совеня', emoji: '🦉' },
    goal: { name: 'Стигле Яблуко', emoji: '🍎' },
    artifact: { name: 'Стигле Яблуко', emoji: '🍏' },
    celebrationEmojis: ['🍃', '🍂', '🌰', '🍄', '🦉'],
    pathIcons: ['🍎', '🍐', '🍑', '🍒', '🌰'],
    dreamBuild: { name: 'Будиночок на Дереві', emoji: '🏡' },
    palette: {
      bg1: '#f7fee7',
      bg2: '#ecfccb',
      surface: '#ffffff',
      surfaceInk: '#3f6212',
      primary: '#65a30d',
      primaryInk: '#ffffff',
      accent: '#d97706',
      accentInk: '#ffffff',
      text: '#365314',
      textSoft: '#5f7a3a',
      ring: '#a3e635',
    },
  },
};

export const THEME_LIST: Theme[] = Object.values(THEMES);
export const DEFAULT_THEME_ID: ThemeId = 'unicorns';
