import type { Theme, ThemeId } from './theme.types';

/**
 * The six launch themes from the PRD "100500 тем" table (§6). Each theme reskins
 * the mascot, collectible artifact, celebration visuals, the solo dream build,
 * and the full colour palette.
 */
export const THEMES: Record<ThemeId, Theme> = {
  /**
   * Neutral, gender-balanced DEFAULT skin used before a child picks a world —
   * a galaxy (Milky Way) look. The child's stored theme is `null` until they
   * choose; everything resolves to this.
   */
  galaxy: {
    id: 'galaxy',
    name: 'Галактика',
    icon: '🌌',
    mascot: { name: 'Зоряний Кораблик', emoji: '🚀' },
    goal: { name: 'Далека Планета', emoji: '🪐' },
    artifact: { name: 'Зірочка', emoji: '⭐' },
    timeToken: { name: 'Зірка', emoji: '⭐' },
    celebrationEmojis: ['⭐', '🌟', '✨', '🪐', '🚀', '☄️'],
    pathIcons: ['⭐', '🪐', '☄️', '🌙', '🛸'],
    dreamBuild: { name: 'Космічна Станція', emoji: '🛰️' },
    chest: { closed: '🛸', open: '✨' },
    treasures: [
      { id: 'star', name: 'Зірка', emoji: '⭐' },
      { id: 'planet', name: 'Планета', emoji: '🪐' },
      { id: 'comet', name: 'Комета', emoji: '☄️' },
      { id: 'moon', name: 'Місяць', emoji: '🌙' },
      { id: 'rocket', name: 'Ракета', emoji: '🚀' },
      { id: 'satellite', name: 'Супутник', emoji: '🛰️' },
      { id: 'ufo', name: 'НЛО', emoji: '🛸' },
      { id: 'galaxy', name: 'Галактика', emoji: '🌌' },
    ],
    palette: {
      bg1: '#0b1026',
      bg2: '#2b1a52',
      surface: '#18213f',
      surfaceInk: '#e8ecff',
      primary: '#7c6cff',
      primaryInk: '#ffffff',
      accent: '#35d6e8',
      accentInk: '#052c33',
      text: '#e8ecff',
      textSoft: '#aab2db',
      ring: '#8b7cff',
    },
  },
  unicorns: {
    id: 'unicorns',
    name: 'Єдинороги',
    icon: '🦄',
    mascot: { name: 'Чарівний Поні', emoji: '🦄' },
    goal: { name: 'Веселка', emoji: '🌈' },
    artifact: { name: 'Сяючий Кристал', emoji: '💎' },
    timeToken: { name: 'Єдиноріг', emoji: '🦄' },
    celebrationEmojis: ['🌈', '⭐', '✨', '💖', '🦄'],
    pathIcons: ['💎', '🌟', '🧁', '🍬', '🌸'],
    dreamBuild: { name: 'Замок Мрій', emoji: '🏰' },
    chest: { closed: '🎁', open: '✨' },
    treasures: [
      { id: 'crown', name: 'Корона', emoji: '👑' },
      { id: 'wand', name: 'Чарівна паличка', emoji: '🪄' },
      { id: 'rainbow', name: 'Веселка', emoji: '🌈' },
      { id: 'orb', name: 'Магічна куля', emoji: '🔮' },
      { id: 'stardust', name: 'Зоряний пил', emoji: '🌟' },
      { id: 'ring', name: 'Чарівний перстень', emoji: '💍' },
      { id: 'fairy', name: 'Фея', emoji: '🧚' },
      { id: 'lolly', name: 'Чарівний льодяник', emoji: '🍭' },
    ],
    palette: {
      bg1: '#fdf2ff',
      bg2: '#ede9fe',
      surface: '#ffffff',
      surfaceInk: '#4c1d95',
      primary: '#a855f7',
      primaryInk: '#ffffff',
      accent: '#f472b6',
      accentInk: '#ffffff',
      text: '#3b0764',
      textSoft: '#7c6a99',
      ring: '#e879f9',
    },
  },
  cars: {
    id: 'cars',
    name: 'Тачки',
    icon: '🏎️',
    mascot: { name: 'Спорткар-Блискавка', emoji: '🏎️' },
    goal: { name: 'Фінішний прапор', emoji: '🏁' },
    artifact: { name: 'Золота Шестерня', emoji: '⚙️' },
    timeToken: { name: 'Пальне', emoji: '⛽' },
    celebrationEmojis: ['🏁', '🏆', '⚙️', '🔥', '🏎️'],
    pathIcons: ['⚙️', '🛞', '🔧', '🏁', '🏆'],
    dreamBuild: { name: 'Гоночне Авто', emoji: '🏎️' },
    chest: { closed: '🧰', open: '💥' },
    treasures: [
      { id: 'cup', name: 'Кубок', emoji: '🏆' },
      { id: 'flag', name: 'Фінішний прапор', emoji: '🏁' },
      { id: 'wrench', name: 'Гайковий ключ', emoji: '🔧' },
      { id: 'gear', name: 'Шестерня', emoji: '⚙️' },
      { id: 'tire', name: 'Колесо', emoji: '🛞' },
      { id: 'light', name: 'Світлофор', emoji: '🚦' },
      { id: 'medal', name: 'Медаль', emoji: '🏅' },
      { id: 'fuel', name: 'Турбо-паливо', emoji: '⛽' },
    ],
    palette: {
      bg1: '#fff7ed',
      bg2: '#fee2e2',
      surface: '#ffffff',
      surfaceInk: '#7f1d1d',
      primary: '#ef4444',
      primaryInk: '#ffffff',
      accent: '#f59e0b',
      accentInk: '#1c1917',
      text: '#7c2d12',
      textSoft: '#9a6a4a',
      ring: '#fb923c',
    },
  },
  space: {
    id: 'space',
    name: 'Космос',
    icon: '🚀',
    mascot: { name: 'Робот-Астронавт', emoji: '🤖' },
    goal: { name: 'Планета', emoji: '🪐' },
    artifact: { name: 'Космічний Метеор', emoji: '☄️' },
    timeToken: { name: 'Ракета', emoji: '🚀' },
    celebrationEmojis: ['⭐', '☄️', '🪐', '✨', '🚀'],
    pathIcons: ['⭐', '🪐', '☄️', '🌙', '🛸'],
    dreamBuild: { name: 'Ракета', emoji: '🚀' },
    chest: { closed: '📦', open: '🌟' },
    treasures: [
      { id: 'ufo', name: 'Літаюча тарілка', emoji: '🛸' },
      { id: 'planet', name: 'Планета', emoji: '🪐' },
      { id: 'comet', name: 'Комета', emoji: '☄️' },
      { id: 'alien', name: 'Прибулець', emoji: '👽' },
      { id: 'moon', name: 'Місяць', emoji: '🌙' },
      { id: 'satellite', name: 'Супутник', emoji: '🛰️' },
      { id: 'star', name: 'Зірка', emoji: '⭐' },
      { id: 'telescope', name: 'Телескоп', emoji: '🔭' },
    ],
    palette: {
      bg1: '#0f172a',
      bg2: '#1e1b4b',
      surface: '#1e293b',
      surfaceInk: '#e0e7ff',
      primary: '#6366f1',
      primaryInk: '#ffffff',
      accent: '#22d3ee',
      accentInk: '#082f49',
      text: '#e2e8f0',
      textSoft: '#94a3b8',
      ring: '#818cf8',
    },
  },
  dinos: {
    id: 'dinos',
    name: 'Динозаври',
    icon: '🦖',
    mascot: { name: 'Динозаврик Рекс', emoji: '🦖' },
    goal: { name: 'Вулкан', emoji: '🌋' },
    artifact: { name: 'Стародавня Мушля', emoji: '🐚' },
    timeToken: { name: 'Яйце динозавра', emoji: '🥚' },
    celebrationEmojis: ['🦖', '🌿', '🦕', '🥚', '🌋'],
    pathIcons: ['🥚', '🦴', '🌿', '🐚', '🌋'],
    dreamBuild: { name: 'Загублений Світ', emoji: '🏝️' },
    chest: { closed: '🥚', open: '🐣' },
    treasures: [
      { id: 'trex', name: 'Ті-Рекс', emoji: '🦖' },
      { id: 'diplo', name: 'Диплодок', emoji: '🦕' },
      { id: 'bone', name: 'Кісточка', emoji: '🦴' },
      { id: 'egg', name: 'Яйце динозавра', emoji: '🥚' },
      { id: 'shell', name: 'Стародавня мушля', emoji: '🐚' },
      { id: 'volcano', name: 'Вулкан', emoji: '🌋' },
      { id: 'fern', name: 'Папороть', emoji: '🌿' },
      { id: 'footprint', name: 'Відбиток лапи', emoji: '🦶' },
    ],
    palette: {
      bg1: '#f0fdf4',
      bg2: '#dcfce7',
      surface: '#ffffff',
      surfaceInk: '#14532d',
      primary: '#16a34a',
      primaryInk: '#ffffff',
      accent: '#ca8a04',
      accentInk: '#ffffff',
      text: '#14532d',
      textSoft: '#4d7c5a',
      ring: '#4ade80',
    },
  },
  underwater: {
    id: 'underwater',
    name: 'Підводний світ',
    icon: '🌊',
    mascot: { name: 'Веселий Крабик', emoji: '🦀' },
    goal: { name: 'Скарб', emoji: '🏴‍☠️' },
    artifact: { name: 'Морська Перлина', emoji: '🫧' },
    timeToken: { name: 'Мушля', emoji: '🐚' },
    celebrationEmojis: ['🫧', '🐠', '🐬', '⭐', '🐚'],
    pathIcons: ['🐚', '🐠', '🪸', '⭐', '🦀'],
    dreamBuild: { name: 'Підводний Човен', emoji: '🚢' },
    chest: { closed: '🦪', open: '🫧' },
    treasures: [
      { id: 'fish', name: 'Рибка', emoji: '🐠' },
      { id: 'dolphin', name: 'Дельфін', emoji: '🐬' },
      { id: 'octopus', name: 'Восьминіг', emoji: '🐙' },
      { id: 'crab', name: 'Крабик', emoji: '🦀' },
      { id: 'shell', name: 'Мушля', emoji: '🐚' },
      { id: 'turtle', name: 'Черепашка', emoji: '🐢' },
      { id: 'treasure', name: 'Піратський скарб', emoji: '🏴‍☠️' },
      { id: 'squid', name: 'Кальмар', emoji: '🦑' },
    ],
    palette: {
      bg1: '#ecfeff',
      bg2: '#cffafe',
      surface: '#ffffff',
      surfaceInk: '#164e63',
      primary: '#0891b2',
      primaryInk: '#ffffff',
      accent: '#f59e0b',
      accentInk: '#1c1917',
      text: '#164e63',
      textSoft: '#4a8296',
      ring: '#22d3ee',
    },
  },
  forest: {
    id: 'forest',
    name: 'Лісова казка',
    icon: '🌿',
    mascot: { name: 'Мудре Совеня', emoji: '🦉' },
    goal: { name: 'Стигле Яблуко', emoji: '🍎' },
    artifact: { name: 'Стигле Яблуко', emoji: '🍏' },
    timeToken: { name: 'Яблучко', emoji: '🍎' },
    celebrationEmojis: ['🍃', '🍂', '🌰', '🍄', '🦉'],
    pathIcons: ['🍎', '🍐', '🍑', '🍒', '🌰'],
    dreamBuild: { name: 'Будиночок на Дереві', emoji: '🏡' },
    chest: { closed: '🧺', open: '🍃' },
    treasures: [
      { id: 'apple', name: 'Яблучко', emoji: '🍎' },
      { id: 'mushroom', name: 'Грибочок', emoji: '🍄' },
      { id: 'acorn', name: 'Жолудь', emoji: '🌰' },
      { id: 'hedgehog', name: 'Їжачок', emoji: '🦔' },
      { id: 'owl', name: 'Совеня', emoji: '🦉' },
      { id: 'pear', name: 'Груша', emoji: '🍐' },
      { id: 'squirrel', name: 'Білочка', emoji: '🐿️' },
      { id: 'sunflower', name: 'Соняшник', emoji: '🌻' },
    ],
    palette: {
      bg1: '#f7fee7',
      bg2: '#ecfccb',
      surface: '#ffffff',
      surfaceInk: '#3f6212',
      primary: '#65a30d',
      primaryInk: '#ffffff',
      accent: '#d97706',
      accentInk: '#ffffff',
      text: '#365314',
      textSoft: '#5f7a3a',
      ring: '#a3e635',
    },
  },
  lego: {
    id: 'lego',
    name: 'Лего',
    icon: '🧱',
    mascot: { name: 'Чоловічок-Будівельник', emoji: '👷' },
    goal: { name: 'Замок із кубиків', emoji: '🏰' },
    artifact: { name: 'Кубик', emoji: '🧱' },
    timeToken: { name: 'Цеглинка', emoji: '🧱' },
    celebrationEmojis: ['🧱', '🟥', '🟨', '🟦', '🟩'],
    pathIcons: ['🧱', '🟥', '🟨', '🟦', '🟩'],
    dreamBuild: { name: 'Велика Споруда', emoji: '🏰' },
    chest: { closed: '📦', open: '🧱' },
    treasures: [
      { id: 'brick', name: 'Цеглинка', emoji: '🧱' },
      { id: 'red', name: 'Червоний блок', emoji: '🟥' },
      { id: 'yellow', name: 'Жовтий блок', emoji: '🟨' },
      { id: 'blue', name: 'Синій блок', emoji: '🟦' },
      { id: 'green', name: 'Зелений блок', emoji: '🟩' },
      { id: 'builder', name: 'Будівельник', emoji: '👷' },
      { id: 'crane', name: 'Підйомний кран', emoji: '🏗️' },
      { id: 'sign', name: 'Знак', emoji: '🚧' },
    ],
    palette: {
      bg1: '#fffbeb',
      bg2: '#fee2e2',
      surface: '#ffffff',
      surfaceInk: '#7f1d1d',
      primary: '#dc2626',
      primaryInk: '#ffffff',
      accent: '#2563eb',
      accentInk: '#ffffff',
      text: '#1e3a8a',
      textSoft: '#6b7280',
      ring: '#fbbf24',
    },
  },
  frozen: {
    id: 'frozen',
    name: 'Крижана казка',
    icon: '❄️',
    mascot: { name: 'Сніговичок', emoji: '⛄' },
    goal: { name: 'Крижаний замок', emoji: '🏰' },
    artifact: { name: 'Сніжинка', emoji: '❄️' },
    timeToken: { name: 'Сніжинка', emoji: '❄️' },
    celebrationEmojis: ['❄️', '✨', '💙', '🩵', '⛄'],
    pathIcons: ['❄️', '⛄', '🩵', '💙', '✨'],
    dreamBuild: { name: 'Крижаний Палац', emoji: '🏰' },
    chest: { closed: '🧊', open: '❄️' },
    treasures: [
      { id: 'snowflake', name: 'Сніжинка', emoji: '❄️' },
      { id: 'snowman', name: 'Сніговичок', emoji: '⛄' },
      { id: 'ice', name: 'Крижинка', emoji: '🧊' },
      { id: 'crystal', name: 'Кришталь', emoji: '🩵' },
      { id: 'heart', name: 'Крижане сердечко', emoji: '💙' },
      { id: 'mountain', name: 'Снігова гора', emoji: '🏔️' },
      { id: 'deer', name: 'Олень', emoji: '🦌' },
      { id: 'spark', name: 'Крижана іскра', emoji: '✨' },
    ],
    palette: {
      bg1: '#f0f9ff',
      bg2: '#e0e7ff',
      surface: '#ffffff',
      surfaceInk: '#1e3a8a',
      primary: '#38bdf8',
      primaryInk: '#083344',
      accent: '#a78bfa',
      accentInk: '#ffffff',
      text: '#1e40af',
      textSoft: '#6b84c0',
      ring: '#7dd3fc',
    },
  },
};

export const THEME_LIST: Theme[] = Object.values(THEMES);
/** The neutral fallback skin used when a child hasn't chosen a theme (null). */
export const DEFAULT_THEME_ID: ThemeId = 'galaxy';
