import { FACTS } from './facts.en.ts';
import type { WorldWords } from './types.ts';
import J from '../../../../locales/app/en/world.json' with { type: 'json' };

/** «Мій світ» in English. Every list keeps the order of the Ukrainian content it lies over. */
export const en: WorldWords = {
  planets: J.planets,
  galaxy: J.galaxy,
  spaceport: J.spaceport,
  facts: FACTS,
  stations: {
    neptune: [
      [J.stations.neptune[0][0], J.stations.neptune[0][1]],
      [J.stations.neptune[1][0], J.stations.neptune[1][1]],
      [J.stations.neptune[2][0], J.stations.neptune[2][1]],
      [J.stations.neptune[3][0], J.stations.neptune[3][1]],
      [J.stations.neptune[4][0], J.stations.neptune[4][1]],
      [J.stations.neptune[5][0], J.stations.neptune[5][1]],
      [J.stations.neptune[6][0], J.stations.neptune[6][1]],
      [J.stations.neptune[7][0], J.stations.neptune[7][1]],
      [J.stations.neptune[8][0], J.stations.neptune[8][1]],
      [J.stations.neptune[9][0], J.stations.neptune[9][1]],
    ],
    uranus: [
      [J.stations.uranus[0][0], J.stations.uranus[0][1]],
      [J.stations.uranus[1][0], J.stations.uranus[1][1]],
      [J.stations.uranus[2][0], J.stations.uranus[2][1]],
      [J.stations.uranus[3][0], J.stations.uranus[3][1]],
      [J.stations.uranus[4][0], J.stations.uranus[4][1]],
      [J.stations.uranus[5][0], J.stations.uranus[5][1]],
      [J.stations.uranus[6][0], J.stations.uranus[6][1]],
      [J.stations.uranus[7][0], J.stations.uranus[7][1]],
      [J.stations.uranus[8][0], J.stations.uranus[8][1]],
      [J.stations.uranus[9][0], J.stations.uranus[9][1]],
    ],
    saturn: [
      [J.stations.saturn[0][0], J.stations.saturn[0][1]],
      [J.stations.saturn[1][0], J.stations.saturn[1][1]],
      [J.stations.saturn[2][0], J.stations.saturn[2][1]],
      [J.stations.saturn[3][0], J.stations.saturn[3][1]],
      [J.stations.saturn[4][0], J.stations.saturn[4][1]],
      [J.stations.saturn[5][0], J.stations.saturn[5][1]],
      [J.stations.saturn[6][0], J.stations.saturn[6][1]],
      [J.stations.saturn[7][0], J.stations.saturn[7][1]],
      [J.stations.saturn[8][0], J.stations.saturn[8][1]],
      [J.stations.saturn[9][0], J.stations.saturn[9][1]],
    ],
    jupiter: [
      [J.stations.jupiter[0][0], J.stations.jupiter[0][1]],
      [J.stations.jupiter[1][0], J.stations.jupiter[1][1]],
      [J.stations.jupiter[2][0], J.stations.jupiter[2][1]],
      [J.stations.jupiter[3][0], J.stations.jupiter[3][1]],
      [J.stations.jupiter[4][0], J.stations.jupiter[4][1]],
      [J.stations.jupiter[5][0], J.stations.jupiter[5][1]],
      [J.stations.jupiter[6][0], J.stations.jupiter[6][1]],
      [J.stations.jupiter[7][0], J.stations.jupiter[7][1]],
      [J.stations.jupiter[8][0], J.stations.jupiter[8][1]],
      [J.stations.jupiter[9][0], J.stations.jupiter[9][1]],
    ],
    mars: [
      [J.stations.mars[0][0], J.stations.mars[0][1]],
      [J.stations.mars[1][0], J.stations.mars[1][1]],
      [J.stations.mars[2][0], J.stations.mars[2][1]],
      [J.stations.mars[3][0], J.stations.mars[3][1]],
      [J.stations.mars[4][0], J.stations.mars[4][1]],
      [J.stations.mars[5][0], J.stations.mars[5][1]],
      [J.stations.mars[6][0], J.stations.mars[6][1]],
      [J.stations.mars[7][0], J.stations.mars[7][1]],
      [J.stations.mars[8][0], J.stations.mars[8][1]],
      [J.stations.mars[9][0], J.stations.mars[9][1]],
    ],
    earth: [
      [J.stations.earth[0][0], J.stations.earth[0][1]],
      [J.stations.earth[1][0], J.stations.earth[1][1]],
      [J.stations.earth[2][0], J.stations.earth[2][1]],
      [J.stations.earth[3][0], J.stations.earth[3][1]],
      [J.stations.earth[4][0], J.stations.earth[4][1]],
      [J.stations.earth[5][0], J.stations.earth[5][1]],
      [J.stations.earth[6][0], J.stations.earth[6][1]],
      [J.stations.earth[7][0], J.stations.earth[7][1]],
      [J.stations.earth[8][0], J.stations.earth[8][1]],
      [J.stations.earth[9][0], J.stations.earth[9][1]],
    ],
    venus: [
      [J.stations.venus[0][0], J.stations.venus[0][1]],
      [J.stations.venus[1][0], J.stations.venus[1][1]],
      [J.stations.venus[2][0], J.stations.venus[2][1]],
      [J.stations.venus[3][0], J.stations.venus[3][1]],
      [J.stations.venus[4][0], J.stations.venus[4][1]],
      [J.stations.venus[5][0], J.stations.venus[5][1]],
      [J.stations.venus[6][0], J.stations.venus[6][1]],
      [J.stations.venus[7][0], J.stations.venus[7][1]],
      [J.stations.venus[8][0], J.stations.venus[8][1]],
      [J.stations.venus[9][0], J.stations.venus[9][1]],
    ],
    mercury: [
      [J.stations.mercury[0][0], J.stations.mercury[0][1]],
      [J.stations.mercury[1][0], J.stations.mercury[1][1]],
      [J.stations.mercury[2][0], J.stations.mercury[2][1]],
      [J.stations.mercury[3][0], J.stations.mercury[3][1]],
      [J.stations.mercury[4][0], J.stations.mercury[4][1]],
      [J.stations.mercury[5][0], J.stations.mercury[5][1]],
      [J.stations.mercury[6][0], J.stations.mercury[6][1]],
      [J.stations.mercury[7][0], J.stations.mercury[7][1]],
      [J.stations.mercury[8][0], J.stations.mercury[8][1]],
      [J.stations.mercury[9][0], J.stations.mercury[9][1]],
    ],
  },
  themes: J.themes,
  visitors: J.visitors,
};
