/**
 * What is told about an animal after a right answer, in English: the texts of
 * `content/animalFacts.ts`, animal by animal, in the same order. One fact per
 * «|». Where the Ukrainian speaks of Ukraine, the English tells its own —
 * marked `own`, as the Ukrainian is.
 */
import { own } from '@/core/lang/marks';

const FACTS: Record<string, string> = {
  giraffe: 'The giraffe is the tallest animal on Earth: it is taller than a two-story house.|Giraffes live in the African savanna — a plain of grass with trees here and there.|A giraffe has as many bones in its neck as a person does — seven.|A giraffe’s tongue is dark blue and almost half a meter long.|A giraffe sleeps only a few hours a day, often standing up.|Every giraffe has its own pattern of spots, like people’s fingerprints.|A giraffe reaches leaves at the tops of acacia trees, where no other animal can stretch.|To have a drink, a giraffe has to spread its front legs wide apart.|A baby giraffe is born two meters tall and is on its feet within an hour.|A giraffe’s heart is very strong: it pumps blood all the way up to its head.',
  lion: 'The lion is called the king of beasts, and it lives in the African savanna.|Lions live in big families called prides.|Only male lions have a mane.|A lion’s roar can be heard several kilometers away.|In a pride it is mostly the lionesses that hunt.|Lions rest for up to twenty hours a day.|Lion cubs are born with spots on their fur, which fade away later.|The lion is the second biggest cat in the world, after the tiger.|A lion has a dark tuft at the tip of its tail.|Lions see well in the dark and often hunt at night.',
  kangaroo: 'Kangaroos live in Australia and are shown on that country’s coat of arms.|A mother kangaroo carries her baby in a pouch on her belly.|A newborn kangaroo is the size of a bean.|A big kangaroo can jump eight meters in one leap.|A kangaroo cannot walk backwards.|Its long, strong tail helps a kangaroo keep its balance.|Kangaroos eat grass and leaves.|Kangaroos can go without water for a long time.|Kangaroos live in groups.|A kangaroo bounds along as fast as a car drives in town.',
  penguin: 'Penguins are birds that cannot fly, but they swim wonderfully.|Under water a penguin paddles with its wings, like flippers.|Thick feathers and a layer of fat protect penguins from the cold.|The emperor penguin is the biggest: it is as tall as a first grader.|Among emperor penguins it is the father who keeps the egg warm: he holds it on his feet.|To keep warm, penguins huddle close together and take turns changing places.|Penguins eat fish, squid and tiny shrimp.|A black back and a white belly hide a penguin in the water from hunters.|Penguins live in the south of the Earth; there are none in the Arctic.|Penguins slide over the snow on their bellies, as if on a sled.',
  panda: 'The giant panda lives in the mountain forests of China.|A panda eats bamboo for more than ten hours a day.|In a day a panda eats more than ten kilograms of bamboo.|A newborn panda is pink and tiny — the size of a stick of butter.|A panda is a bear, but it does not sleep through the winter.|On its front paws a panda has a “sixth finger” for holding bamboo.|Pandas are good at climbing trees.|The panda is a symbol of protecting nature all over the world.|Pandas like to live alone.|The black patches around the eyes are a little different on every panda.',
  llama: 'The llama lives in the Andes — the mountains of South America.|Llamas are relatives of camels, only without humps.|People tamed llamas thousands of years ago to carry loads.|If you make a llama angry, it may spit.|Warm sweaters and blankets are knitted from llama wool.|Llamas feel fine high in the mountains, where the air is thin.|Llamas eat grass.|Llamas talk to one another with a quiet hum.|If its load is too heavy, a llama lies down and refuses to go.|Llamas are kept with flocks of sheep: they drive hunters away.',
  bison: 'The bison is the biggest animal of North America.|A bison weighs as much as a small car.|For all its weight, a bison runs very fast.|Millions of bison once roamed the prairies of America.|In winter a bison sweeps the snow aside with its head to get at the grass.|Thick fur protects a bison from frost and blizzards.|Bison live in herds.|A bison calf is reddish, and it turns darker as it grows up.|The bison’s European relative is the wisent, which lives in the forests of Europe.|The hump on a bison’s back is strong muscle that holds up its heavy head.',
  hedgehog: 'The hedgehog lives in the forests and gardens of Europe.|There are several thousand spines on a hedgehog’s back.|In danger a hedgehog rolls up into a prickly ball.|Hedgehogs go out walking at night.|A hedgehog eats beetles, caterpillars, slugs and worms.|In winter a hedgehog sleeps in a pile of leaves right through to spring.|Hedgehogs do not carry apples and mushrooms on their spines — that is a story from fairy tales.|Baby hedgehogs are born with soft white spines.|A hedgehog has a wonderful sense of smell and hearing, but it sees poorly.|Hedgehogs must not be given milk — it gives them a stomachache.',
  koala: 'The koala lives in the eucalyptus trees of Australia.|A koala eats nothing but eucalyptus leaves.|A koala sleeps for up to twenty hours a day.|A koala is not a bear but a pouched animal, like a kangaroo.|A baby koala grows in its mother’s pouch for half a year.|A koala hardly ever drinks: it gets enough water from the leaves.|A koala’s fingerprints are very like a person’s.|A mother koala carries her older baby on her back.|Koalas seldom come down to the ground.|Eucalyptus leaves are poisonous for most animals, but they do a koala no harm.',
  tiger: 'The tiger is the biggest cat in the world.|Every tiger has its own stripes, like people’s fingerprints.|Tigers live in Asia: in India, in China and in the Far East.|Tigers love water and swim well.|A tiger hunts alone, and usually at night.|The skin under a tiger’s fur is striped too.|A tiger can leap more than six meters.|Its stripes hide a tiger in tall grass and thickets.|Tiger cubs stay with their mother for about two years.|Few tigers are left in the wild, so they are protected.',
  polar_bear: 'The polar bear is the biggest hunter on land.|A polar bear’s skin is black, and its hairs are see-through.|A polar bear swims wonderfully and can cover dozens of kilometers.|Polar bears hunt seals from the ice.|A thick layer of fat keeps a polar bear warm in the frost.|Cubs are born in winter in a den of snow.|A polar bear can smell a seal from many kilometers away.|Wide paws keep a polar bear from sinking into the snow.|Polar bears live only in the north, around the North Pole.|Polar bears need ice: without it they find it hard to hunt.',
  camel: 'A camel can go without water for more than a week.|A camel’s humps hold not water but fat — a store of food.|A camel can drink more than a hundred liters of water at one go.|Long eyelashes and nostrils that close protect a camel from the sand.|Wide feet keep a camel from sinking into the sand.|The camel is called the ship of the desert.|There are camels with one hump and camels with two.|Camels eat even thorns.|People have ridden camels and carried loads on them for thousands of years.|A camel easily stands both the heat of the day and the cold of the desert night.',
  monkey: 'Monkeys live in warm forests and climb trees nimbly.|Many monkeys hold on to branches with their tail, as with a fifth hand.|Monkeys live in big groups.|Monkeys eat fruit, leaves, nuts and insects.|Monkeys clean one another’s fur — that is how they make friends.|Monkeys are very clever and can use sticks and stones.|A baby monkey clings to its mother’s fur.|Monkeys warn one another of danger with cries.|The smallest monkey — the marmoset — fits on the palm of a hand.|Monkeys are the closest relatives of people among the animals.',
  dolphin: 'A dolphin is not a fish: it breathes air.|A dolphin breathes through a hole on the top of its head — the blowhole.|Dolphins “talk” in whistles and clicks.|A dolphin finds its prey by echoes.|When a dolphin sleeps, half of its brain stays awake and minds its breathing.|Dolphins live in pods and help one another.|Baby dolphins drink their mother’s milk.|Dolphins love to play and leap out of the water.|Dolphins are among the cleverest of animals.|Every dolphin has a special whistle of its own — like a name.',
  seal: 'A seal swims wonderfully, but moves clumsily on land.|A thick layer of fat keeps a seal warm in icy water.|A seal can hold its breath under water for half an hour and more.|With its whiskers a seal feels fish moving in the water.|Seals eat fish, squid and shrimp.|Seal pups are born on the ice in a fluffy white coat.|Seals rest on ice floes and rocks.|To breathe under the ice, a seal makes holes in it.|The seals’ main enemies are polar bears and killer whales.|Instead of paws a seal has flippers.',
  parrot: 'Parrots live in warm tropical forests.|Some parrots can repeat people’s words.|With its strong beak a parrot cracks nuts.|A parrot picks up food with its foot, as with a hand.|Big parrots can live for more than fifty years.|Bright feathers hide parrots among flowers and leaves.|Parrots live in noisy flocks.|Parrots nest in the hollows of trees.|On a parrot’s foot two toes point forward and two point back.|Parrots are very clever and can solve puzzles.',
  scorpion: 'A scorpion is a relative of spiders: it has eight legs.|At the end of its tail a scorpion has a sting with poison.|By day a scorpion hides under stones, and it hunts at night.|Scorpions glow under an ultraviolet flashlight.|Scorpions lived on Earth even before the dinosaurs.|A mother scorpion carries her babies on her back.|A scorpion can go without eating for many months.|With its pincers a scorpion grabs insects.|Most scorpions are not dangerous to people, but they must not be touched.|A scorpion feels the steps of its prey by the trembling of the sand.',
  octopus: 'An octopus has eight arms and three hearts.|An octopus’s blood is blue.|An octopus can change color and become hard to see.|An octopus has no bones, so it squeezes into narrow cracks.|In danger an octopus squirts out a little cloud of ink.|Octopuses are very clever and can open jars.|There are hundreds of suckers on an octopus’s arms.|If an octopus loses an arm, it grows back.|An octopus lives on the seabed among the stones.|An octopus tastes with its suckers.',
  arctic_hare: 'The arctic hare is white in winter, so that it cannot be seen on the snow.|An arctic hare’s ears are shorter than an ordinary hare’s — that way it gets less cold.|An arctic hare can speed up to sixty kilometers an hour.|In winter arctic hares gather in big groups.|An arctic hare digs moss and twigs out from under the snow.|The thick fur on an arctic hare’s paws works like snowshoes.|An arctic hare stands up on its hind legs to look around.|An arctic hare hides from the wind in a hollow in the snow.|Baby hares are born with fur and with their eyes open.|Arctic hares are hunted by arctic foxes, wolves and snowy owls.',
  lizard: 'A lizard basks in the sun, because its body makes no warmth of its own.|In danger a lizard can drop its tail — a new one will grow later.|Lizards eat insects.|A lizard’s skin is covered with little scales.|Lizards lay their eggs in the sand.|Desert lizards lift their feet in turn, so as not to burn them on the sand.|Some lizards run on walls and ceilings.|Lizards, snakes and crocodiles are reptiles.|The biggest lizard in the world is the Komodo dragon.|A lizard flicks out its tongue to “smell” the air.',
  whale: 'The blue whale is the biggest animal that has ever lived on Earth.|A whale is not a fish: it breathes air and feeds its young with milk.|The heart of a blue whale is the size of a small car.|Whales “sing” under water, and their songs can be heard very far away.|A whale’s fountain is the air it breathes out.|The blue whale eats tiny shrimp.|Every year whales swim thousands of kilometers.|A whale calf drinks hundreds of liters of milk a day.|Instead of teeth many whales have horny plates called baleen.|Whales can live for more than eighty years.',
  shark: 'Sharks lived in the ocean even before the dinosaurs.|A shark has no bones — its skeleton is made of gristle.|A shark’s teeth grow in rows and are replaced all its life.|A shark can smell its prey from very far away.|The biggest shark — the whale shark — eats only plankton and is harmless to people.|A shark’s skin is rough, like sandpaper.|Most sharks have to keep swimming all the time in order to breathe.|Sharks feel the faint electric signals of other animals.|Sharks very seldom attack people.|Sharks matter to the ocean: they keep it in balance.',
  gorilla: 'The gorilla is the biggest ape in the world.|Gorillas live in the forests of Africa.|Gorillas eat leaves, stems and fruit.|A gorilla family is led by a big male with a silver back.|Every evening gorillas build themselves a nest to sleep in.|Gorillas walk leaning on their knuckles.|Gorillas are very strong, but peaceful.|Gorillas can learn sign language.|A baby gorilla rides on its mother’s back.|Few gorillas are left, so they are protected.',
  snake: 'A snake has no legs: it crawls by bending its body.|A snake “smells” with its tongue.|A snake swallows its prey whole.|Snakes shed their old skin as they grow.|Snakes have no eyelids — they do not blink.|By day desert snakes hide in the sand from the heat.|Snakes feel footsteps by the trembling of the ground.|Not all snakes are poisonous.|After a hearty meal a snake may not eat for several weeks.|Some desert snakes crawl sideways, to touch the hot sand less.',
  arctic_fox: 'The arctic fox is white in winter and gray-brown in summer.|The fur of the arctic fox is among the warmest of any animal.|An arctic fox does not freeze even in fifty degrees of frost.|An arctic fox hears lemmings under the snow and dives into the drift after them.|An arctic fox covers itself with its fluffy tail, as with a blanket.|An arctic fox’s paws are furry even underneath.|Arctic foxes live in burrows with many ways out.|Arctic foxes often follow polar bears and finish what they leave.|An arctic fox has small ears and a short nose — that way it loses less warmth.|A family of arctic foxes may have more than ten cubs.',
  zebra: 'Every zebra has its own pattern of stripes — like people’s fingerprints.|Zebras live in the savanna in big herds — that makes it easier to spot a hunter.|The zebra is a relative of the horse, but it is almost impossible to tame.|Zebras sleep standing up, and one of the herd always keeps watch.|A zebra foal gets to its feet just a few minutes after it is born.|A zebra’s stripes confuse biting flies — they land on it less often.',
  elephant: 'The elephant is the biggest animal on land.|With its trunk an elephant breathes, drinks, picks leaves and even hugs.|An elephant fans itself with its big ears to keep cool.|Elephants have a wonderful memory and remember the way to water for years.|A herd of elephants is led by the oldest and wisest female.|A baby elephant is born weighing about a hundred kilograms and can walk right away.',
  rhino: 'A rhino’s horn is made of the same stuff as our fingernails.|A rhino sees poorly, but it hears and smells wonderfully.|Rhinos love to roll in mud — it protects their skin from the sun and from insects.|For all its weight, a rhino runs faster than a person.|Rhinos eat only plants: grass, leaves and twigs.|Little birds often sit on a rhino’s back — they peck insects out of its skin.',
  brown_bear: 'In winter the brown bear sleeps in its den and does not eat for several months.|A brown bear eats almost everything: berries, nuts, fish, honey.|Bear cubs are born in winter in the den — tiny, like kittens.|A brown bear climbs trees wonderfully and swims well.|A bear’s sense of smell is far better than a dog’s.|' + own('Brown bears live in the Carpathian Mountains of Europe too.'),
  wolf: 'Wolves live in a pack — a big, close family.|Wolves howl to call their own and to tell strangers: this is our land.|The wolf is the ancestor of all dogs.|In one night a wolf pack can run dozens of kilometers.|All the grown wolves in a pack look after the cubs.|Wolves hear sounds several kilometers away.',
  squirrel: 'A squirrel lays in stores for the winter: it hides nuts and acorns.|A squirrel often forgets its hiding places — and new trees grow from them.|Its fluffy tail helps a squirrel keep its balance when it jumps.|A squirrel’s nest is called a drey — it is round and warm.|A squirrel’s teeth grow all its life, so it is always gnawing something.|In winter a squirrel’s coat grows thicker and grayer.',
  owl: 'An owl hunts at night: it sees wonderfully in the dark.|An owl flies almost without a sound, thanks to its soft feathers.|An owl cannot move its eyes, but it turns its head far around.|An owl’s hearing is so sharp that it hears a mouse under the snow.|By day an owl sleeps in a hollow or among thick branches.|Baby owls are called owlets — they are covered in white down.',
  deer: 'A deer’s antlers fall off every year, and new ones grow.|Fawns are born with white spots — that makes them harder to see in the grass.|Among forest deer only the males carry antlers.|A deer eats grass, leaves, bark and acorns.|In the fall deer bellow loudly — it can be heard all through the forest.|A deer is very shy and runs away in great leaps.',
  boar: 'A wild boar digs up the ground with its snout, looking for roots, acorns and beetles.|A boar’s young are striped — the stripes hide them among the leaves.|The wild boar is the ancestor of the farm pig.|Boars love to bathe in mud to get rid of insects.|A boar has sharp tusks, which it defends itself with.|Boars swim well and run fast.',
  sea_turtle: 'A sea turtle can live for more than half a century.|Sea turtles lay their eggs on the very beach where they hatched themselves.|Instead of paws a sea turtle has flippers.|A sea turtle swims thousands of kilometers across the ocean.|Little turtles run to the sea as soon as they hatch.|Sea turtles lived back in the time of the dinosaurs.',
  orangutan: 'An orangutan spends almost all its life in the trees.|The name “orangutan” means “person of the forest.”|Every evening an orangutan builds itself a new nest of branches in a tree.|An orangutan’s arms are longer than its legs — they are handy for holding on to branches.|An orangutan is very clever: it uses little sticks as tools.|An orangutan hides from the rain under a big leaf, as under an umbrella.',
  crab: 'A crab walks sideways.|A crab has ten legs, and two of them are pincers.|A crab’s shell does not grow, so the crab sheds it and grows a new one.|A crab can grow back a pincer it has lost.|A crab’s eyes sit on little stalks and look in different directions.|The biggest crab in the world measures almost four meters from leg tip to leg tip.',
  sloth: 'The sloth is the slowest animal in the world.|A sloth sleeps hanging from a branch with its back down.|Tiny green plants grow in a sloth’s fur — they make it look greenish.|A sloth comes down to the ground about once a week.|A sloth swims better than it walks.|A sloth eats leaves and takes many days to digest them.',
  jellyfish: 'A jellyfish is made almost entirely of water.|A jellyfish has no brain, no heart and no bones.|Jellyfish lived in the ocean even before the dinosaurs.|Some jellyfish glow in the dark.|A jellyfish’s tentacles sting, so you must not touch it.|A jellyfish moves by squeezing its bell, like an umbrella.',
  clownfish: 'A clownfish lives among the tentacles of a sea anemone, which sting other fish but not it.|A clownfish is bright orange with white stripes.|A clownfish cleans its anemone, and the anemone protects it.|Clownfish live on warm coral reefs.|A clownfish never swims far from its home.|A clownfish’s eggs are guarded by the father.',
  squid: 'A squid swims by pushing water out — like a little rocket.|A squid has eight arms and two long tentacles.|In danger a squid squirts out a cloud of ink.|A squid can change color in an instant.|A giant squid has eyes the size of a big plate.|A squid has three hearts.',
  mountain_goat: 'A mountain goat leaps about on almost sheer cliffs and does not fall.|A mountain goat’s hooves grip like a climber’s boots.|Thick fur keeps a mountain goat warm on the cold peaks.|Kids are climbing the rocks just a day after they are born.|High in the mountains, mountain goats hide from hunters.|Mountain goats eat grass, moss and lichen.',
  eagle: 'An eagle sees its prey from a very great height.|An eagle builds its nest on high cliffs and uses it for many years.|An eagle’s wingspan is greater than the height of a grown person.|An eagle soars in the air, hardly flapping its wings.|An eagle has strong claws and a hooked beak.|A pair of eagles stays together for life.',
  mountain_ram: 'A mountain ram has big curling horns.|You can tell a mountain ram’s age by its horns — as by the rings of a tree.|Mountain rams live high in the mountains, where there are few hunters.|Rams find out who is stronger by knocking horns.|A mountain ram leaps easily from rock to rock.|In winter mountain rams come down lower, where there is less snow.',
};

export const ANIMAL_FACTS: Record<string, string[]> = Object.fromEntries(Object.entries(FACTS).map(([id, text]) => [id, text.split('|')]));
