/**
 * What is told about an animal after a right answer, in Polish: the texts of
 * `content/animalFacts.ts`, animal by animal, in the same order. One fact per
 * «|». Where the Ukrainian speaks of Ukraine, the Polish speaks of Poland —
 * marked `own`, as the Ukrainian is.
 */
import { own } from '@/core/lang/marks';

const FACTS: Record<string, string> = {
  giraffe: 'Żyrafa to najwyższe zwierzę na Ziemi: jest wyższa od piętrowego domu.|Żyrafy żyją na afrykańskiej sawannie — równinie porośniętej trawą i pojedynczymi drzewami.|W szyi żyrafy jest tyle samo kości co w szyi człowieka — siedem.|Język żyrafy jest ciemnoniebieski i ma prawie pół metra długości.|Żyrafa śpi tylko kilka godzin na dobę, często na stojąco.|Każda żyrafa ma własny wzór z plam, tak jak ludzie mają odciski palców.|Żyrafa sięga po liście z czubków akacji, dokąd nie dosięgnie żadne inne zwierzę.|Żeby się napić, żyrafa musi szeroko rozstawić przednie nogi.|Mała żyrafa rodzi się wysoka na dwa metry i już po godzinie staje na nogi.|Serce żyrafy jest bardzo silne: pompuje krew aż do głowy.',
  lion: 'Lwa nazywa się królem zwierząt, a mieszka on na afrykańskiej sawannie.|Lwy żyją w dużych rodzinach — stadach.|Grzywę mają tylko samce lwów.|Ryk lwa słychać z odległości kilku kilometrów.|W stadzie polują przeważnie lwice.|Lwy odpoczywają nawet dwadzieścia godzin na dobę.|Lwiątka rodzą się z plamkami na sierści, które później znikają.|Lew to drugi co do wielkości kot na świecie, po tygrysie.|Na końcu ogona lew ma ciemny pędzelek.|Lwy dobrze widzą w ciemności i często polują nocą.',
  kangaroo: 'Kangury żyją w Australii i są przedstawione w herbie tego kraju.|Mama kangurzyca nosi malucha w torbie na brzuchu.|Nowo narodzony kangurek jest wielkości fasolki.|Duży kangur potrafi skoczyć na osiem metrów w dal.|Kangur nie umie chodzić do tyłu.|Długi, silny ogon pomaga kangurowi utrzymać równowagę.|Kangury jedzą trawę i liście.|Kangury mogą długo obywać się bez wody.|Kangury żyją w grupach.|Kangur pędzi skokami tak szybko, jak samochód jedzie w mieście.',
  penguin: 'Pingwiny to ptaki, które nie latają, za to świetnie pływają.|Pod wodą pingwin wiosłuje skrzydłami jak płetwami.|Przed zimnem chronią pingwiny gęste pióra i warstwa tłuszczu.|Pingwin cesarski jest największy: wzrostem dorównuje pierwszoklasiście.|U pingwinów cesarskich jajo ogrzewa tata: trzyma je na łapach.|Żeby się ogrzać, pingwiny stają w ciasnej gromadzie i po kolei zamieniają się miejscami.|Pingwiny jedzą ryby, kałamarnice i małe skorupiaki.|Czarny grzbiet i biały brzuch ukrywają pingwina w wodzie przed drapieżnikami.|Pingwiny żyją na południu Ziemi; w Arktyce ich nie ma.|Po śniegu pingwiny ślizgają się na brzuchu jak na sankach.',
  panda: 'Panda wielka żyje w górskich lasach Chin.|Panda je bambus ponad dziesięć godzin dziennie.|W ciągu dnia panda zjada ponad dziesięć kilogramów bambusa.|Nowo narodzona panda jest różowa i maleńka — wielkości kostki masła.|Panda to niedźwiedź, ale nie zapada w sen zimowy.|Na przednich łapach panda ma „szósty palec”, którym trzyma bambus.|Pandy dobrze wspinają się na drzewa.|Panda jest symbolem ochrony przyrody na całym świecie.|Pandy lubią żyć samotnie.|Czarne plamy wokół oczu są u każdej pandy trochę inne.',
  llama: 'Lama żyje w Andach — górach Ameryki Południowej.|Lamy to krewne wielbłądów, tylko bez garbów.|Ludzie oswoili lamy tysiące lat temu, żeby nosiły ładunki.|Rozzłoszczona lama potrafi splunąć.|Z wełny lamy robi się na drutach ciepłe swetry i koce.|Lamy dobrze czują się wysoko w górach, gdzie jest mało powietrza.|Lamy jedzą trawę.|Lamy porozumiewają się cichym buczeniem.|Jeśli ładunek jest za ciężki, lama kładzie się i nie chce iść.|Lamy trzyma się razem ze stadami owiec: odpędzają drapieżniki.',
  bison: 'Bizon to największe zwierzę Ameryki Północnej.|Bizon waży tyle co mały samochód.|Mimo dużej wagi bizon biega bardzo szybko.|Kiedyś po amerykańskich preriach wędrowały miliony bizonów.|Zimą bizon odgarnia śnieg głową, żeby dostać się do trawy.|Gęsta sierść chroni bizona przed mrozem i zamiecią.|Bizony żyją w stadach.|Cielę bizona jest rude, a gdy dorasta — ciemnieje.|Europejski krewny bizona to żubr' + own(', który żyje także w Polsce') + '.|Garb na grzbiecie bizona to silne mięśnie, które dźwigają ciężką głowę.',
  hedgehog: 'Jeż żyje w lasach i ogrodach Europy' + own(', także w Polsce') + '.|Na grzbiecie jeża jest kilka tysięcy kolców.|W razie niebezpieczeństwa jeż zwija się w kolczastą kulkę.|Jeże wychodzą na spacer nocą.|Jeż je chrząszcze, gąsienice, ślimaki i dżdżownice.|Zimą jeż śpi w stercie liści aż do wiosny.|Jeże nie noszą jabłek i grzybów na kolcach — to wymysł z bajek.|Małe jeże rodzą się z miękkimi białymi kolcami.|Jeż ma świetny węch i słuch, ale słabo widzi.|Jeżom nie wolno dawać mleka — boli je od niego brzuch.',
  koala: 'Koala żyje na eukaliptusach w Australii.|Koala je tylko liście eukaliptusa.|Koala śpi nawet dwadzieścia godzin na dobę.|Koala to nie niedźwiedź, tylko torbacz, jak kangur.|Mały koala przez pół roku rośnie w torbie mamy.|Koala prawie nie pije: wody wystarcza mu z liści.|Odciski palców koali są bardzo podobne do ludzkich.|Podrośniętego malucha mama koala nosi na grzbiecie.|Koale rzadko schodzą na ziemię.|Liście eukaliptusa są trujące dla większości zwierząt, a koali nie szkodzą.',
  tiger: 'Tygrys to największy kot na świecie.|Każdy tygrys ma własne paski, tak jak ludzie mają odciski palców.|Tygrysy żyją w Azji: w Indiach, Chinach i na Dalekim Wschodzie.|Tygrysy lubią wodę i dobrze pływają.|Tygrys poluje sam i zwykle nocą.|Skóra pod sierścią tygrysa też jest w paski.|Tygrys potrafi skoczyć na ponad sześć metrów w dal.|Paski ukrywają tygrysa w wysokiej trawie i zaroślach.|Tygrysiątka zostają z mamą około dwóch lat.|Tygrysów na wolności zostało mało, dlatego się je chroni.',
  polar_bear: 'Niedźwiedź polarny to największy drapieżnik na lądzie.|Skóra niedźwiedzia polarnego jest czarna, a włosy przezroczyste.|Niedźwiedź polarny świetnie pływa i potrafi przepłynąć dziesiątki kilometrów.|Niedźwiedzie polarne polują na foki z lodu.|Gruba warstwa tłuszczu grzeje niedźwiedzia polarnego w mróz.|Niedźwiadki rodzą się zimą w śnieżnej gawrze.|Niedźwiedź polarny czuje zapach foki z odległości wielu kilometrów.|Szerokie łapy nie pozwalają niedźwiedziowi polarnemu zapadać się w śnieg.|Niedźwiedzie polarne żyją tylko na północy, wokół bieguna północnego.|Niedźwiedziom polarnym potrzebny jest lód: bez niego trudno im polować.',
  camel: 'Wielbłąd może obyć się bez wody ponad tydzień.|W garbach wielbłąda nie ma wody, tylko tłuszcz — zapas jedzenia.|Za jednym razem wielbłąd potrafi wypić ponad sto litrów wody.|Długie rzęsy i zamykane nozdrza chronią wielbłąda przed piaskiem.|Szerokie stopy nie pozwalają wielbłądowi zapadać się w piasek.|Wielbłąda nazywa się okrętem pustyni.|Bywają wielbłądy z jednym garbem i z dwoma.|Wielbłądy jedzą nawet kolczaste rośliny.|Ludzie jeżdżą na wielbłądach i przewożą na nich ładunki od tysięcy lat.|Wielbłąd dobrze znosi i dzienny upał, i nocny chłód pustyni.',
  monkey: 'Małpy żyją w ciepłych lasach i zwinnie wspinają się po drzewach.|Wiele małp trzyma się gałęzi ogonem jak piątą ręką.|Małpy żyją w dużych grupach.|Małpy jedzą owoce, liście, orzechy i owady.|Małpy czyszczą sobie nawzajem sierść — tak się przyjaźnią.|Małpy są bardzo bystre i potrafią używać patyków i kamieni.|Mała małpka trzyma się sierści mamy.|Małpy ostrzegają się nawzajem przed niebezpieczeństwem krzykiem.|Najmniejsza małpka — marmozeta — mieści się na dłoni.|Małpy to najbliżsi krewni człowieka wśród zwierząt.',
  dolphin: 'Delfin to nie ryba: oddycha powietrzem.|Delfin oddycha przez otwór na czubku głowy — nozdrze.|Delfiny „rozmawiają” gwizdami i klikaniem.|Delfin znajduje zdobycz dzięki echu.|Kiedy delfin śpi, połowa jego mózgu czuwa i pilnuje oddychania.|Delfiny żyją w stadach i pomagają sobie nawzajem.|Małe delfiny piją mleko mamy.|Delfiny lubią się bawić i wyskakiwać z wody.|Delfiny należą do najmądrzejszych zwierząt.|Każdy delfin ma swój własny gwizd — jak imię.',
  seal: 'Foka świetnie pływa, a na lądzie porusza się niezgrabnie.|Gruba warstwa tłuszczu grzeje fokę w lodowatej wodzie.|Foka może nie oddychać pod wodą pół godziny i dłużej.|Wąsami foka wyczuwa ruch ryb w wodzie.|Foki jedzą ryby, kałamarnice i skorupiaki.|Małe foki rodzą się na lodzie w białym, puszystym futerku.|Foki odpoczywają na krach i skałach.|Żeby oddychać pod lodem, foka robi w nim otwory.|Głównymi wrogami fok są niedźwiedzie polarne i orki.|Zamiast łap foka ma płetwy.',
  parrot: 'Papugi żyją w ciepłych lasach tropikalnych.|Niektóre papugi potrafią powtarzać ludzkie słowa.|Mocnym dziobem papuga rozłupuje orzechy.|Papuga bierze jedzenie łapą jak ręką.|Duże papugi mogą żyć ponad pięćdziesiąt lat.|Jaskrawe pióra ukrywają papugi wśród kwiatów i liści.|Papugi żyją w hałaśliwych stadach.|Papugi gniazdują w dziuplach drzew.|Na łapie papugi dwa palce są skierowane do przodu, a dwa do tyłu.|Papugi są bardzo mądre i potrafią rozwiązywać łamigłówki.',
  scorpion: 'Skorpion to krewny pająków: ma osiem nóg.|Na końcu ogona skorpion ma kolec z jadem.|W dzień skorpion chowa się pod kamieniami, a poluje nocą.|Skorpiony świecą w świetle latarki ultrafioletowej.|Skorpiony żyły na Ziemi jeszcze przed dinozaurami.|Mama skorpionica nosi młode na grzbiecie.|Skorpion może nie jeść przez wiele miesięcy.|Szczypcami skorpion chwyta owady.|Większość skorpionów nie jest groźna dla człowieka, ale nie wolno ich dotykać.|Skorpion wyczuwa kroki zdobyczy po drganiach piasku.',
  octopus: 'Ośmiornica ma osiem ramion i trzy serca.|Krew ośmiornicy jest niebieska.|Ośmiornica potrafi zmieniać kolor i stawać się niewidoczna.|Ośmiornica nie ma kości, dlatego wciska się w wąskie szczeliny.|W razie niebezpieczeństwa ośmiornica wypuszcza chmurkę atramentu.|Ośmiornice są bardzo mądre i potrafią otwierać słoiki.|Na ramionach ośmiornicy są setki przyssawek.|Jeśli ośmiornica straci ramię, ono odrośnie.|Ośmiornica żyje na dnie morza wśród kamieni.|Przyssawkami ośmiornica czuje smak.',
  arctic_hare: 'Zając polarny jest zimą biały, żeby nie było go widać na śniegu.|Uszy zająca polarnego są krótsze niż u zwykłego zająca — dzięki temu mniej marznie.|Zając polarny rozpędza się do sześćdziesięciu kilometrów na godzinę.|Zimą zające polarne zbierają się w duże gromady.|Zając polarny wygrzebuje spod śniegu mech i gałązki.|Gęste futro na łapach zająca polarnego działa jak rakiety śnieżne.|Zając polarny staje na tylnych łapach, żeby się rozejrzeć.|Przed wiatrem zając polarny chowa się w dołku w śniegu.|Zajączki rodzą się z futerkiem i otwartymi oczami.|Na zające polarne polują lisy polarne, wilki i sowy śnieżne.',
  lizard: 'Jaszczurka wygrzewa się na słońcu, bo jej ciało samo nie wytwarza ciepła.|W razie niebezpieczeństwa jaszczurka może odrzucić ogon — potem wyrośnie nowy.|Jaszczurki jedzą owady.|Skóra jaszczurki jest pokryta łuskami.|Jaszczurki składają jaja w piasku.|Pustynne jaszczurki na zmianę podnoszą łapki, żeby nie poparzyć się o piasek.|Niektóre jaszczurki biegają po ścianach i suficie.|Jaszczurki, węże i krokodyle to gady.|Największa jaszczurka na świecie to waran z Komodo.|Jaszczurka wysuwa język, żeby „powąchać” powietrze.',
  whale: 'Płetwal błękitny to największe zwierzę, jakie kiedykolwiek żyło na Ziemi.|Wieloryb to nie ryba: oddycha powietrzem i karmi młode mlekiem.|Serce płetwala błękitnego jest wielkości małego samochodu.|Wieloryby „śpiewają” pod wodą, a ich pieśni słychać bardzo daleko.|Fontanna wieloryba to powietrze, które wydycha.|Płetwal błękitny je maleńkie skorupiaki.|Wieloryby co roku przepływają tysiące kilometrów.|Młody wieloryb wypija dziennie setki litrów mleka.|Zamiast zębów wiele wielorybów ma rogowe płyty — fiszbiny.|Wieloryby mogą żyć ponad osiemdziesiąt lat.',
  shark: 'Rekiny żyły w oceanie jeszcze przed dinozaurami.|Rekin nie ma kości — jego szkielet jest zbudowany z chrząstki.|Zęby rekina rosną rzędami i wymieniają się przez całe życie.|Rekin wyczuwa zapach zdobyczy z bardzo daleka.|Największy rekin — wielorybi — je tylko plankton i nie jest groźny dla ludzi.|Skóra rekina jest szorstka jak papier ścierny.|Większość rekinów musi stale płynąć, żeby oddychać.|Rekiny wyczuwają słabe sygnały elektryczne innych zwierząt.|Rekiny bardzo rzadko atakują ludzi.|Rekiny są ważne dla oceanu: utrzymują w nim równowagę.',
  gorilla: 'Goryl to największa małpa na świecie.|Goryle żyją w lasach Afryki.|Goryle jedzą liście, łodygi i owoce.|Rodzinę goryli prowadzi duży samiec ze srebrzystym grzbietem.|Co wieczór goryle budują sobie gniazdo do spania.|Goryle chodzą, podpierając się na knykciach.|Goryle są bardzo silne, ale łagodne.|Goryle potrafią nauczyć się języka migowego.|Mały goryl jeździ na grzbiecie mamy.|Goryli zostało mało, dlatego się je chroni.',
  snake: 'Wąż nie ma nóg: pełza, wyginając ciało.|Wąż „wącha” językiem.|Wąż połyka zdobycz w całości.|Węże zrzucają starą skórę, gdy rosną.|Węże nie mają powiek — nie mrugają.|Pustynne węże w dzień chowają się w piasku przed upałem.|Węże wyczuwają kroki po drganiach ziemi.|Nie wszystkie węże są jadowite.|Po sytym posiłku wąż może nie jeść przez kilka tygodni.|Niektóre pustynne węże pełzają bokiem, żeby mniej dotykać gorącego piasku.',
  arctic_fox: 'Lis polarny jest zimą biały, a latem szarobrązowy.|Futro lisa polarnego należy do najcieplejszych wśród zwierząt.|Lis polarny nie marznie nawet przy pięćdziesięciu stopniach mrozu.|Lis polarny słyszy lemingi pod śniegiem i nurkuje za nimi w zaspę.|Puszystym ogonem lis polarny okrywa się jak kołdrą.|Łapy lisa polarnego są pokryte futrem nawet od spodu.|Lisy polarne żyją w norach z wieloma wyjściami.|Lisy polarne często chodzą za niedźwiedziami polarnymi i dojadają resztki.|Lis polarny ma małe uszy i krótki nos — dzięki temu traci mniej ciepła.|W rodzinie lisów polarnych bywa ponad dziesięcioro młodych.',
  zebra: 'Każda zebra ma własny wzór z pasków — jak ludzie odciski palców.|Zebry żyją na sawannie w dużych stadach — tak łatwiej zauważyć drapieżnika.|Zebra to krewna konia, ale prawie nie da się jej oswoić.|Zebry śpią na stojąco, a ktoś ze stada zawsze stoi na straży.|Źrebię zebry staje na nogi już kilka minut po urodzeniu.|Paski zebry mylą gryzące muchy — rzadziej na niej siadają.',
  elephant: 'Słoń to największe zwierzę na lądzie.|Trąbą słoń oddycha, pije, zrywa liście, a nawet się przytula.|Wielkimi uszami słoń się wachluje, żeby nie było mu gorąco.|Słonie mają świetną pamięć i latami pamiętają drogę do wody.|Stado słoni prowadzi najstarsza i najmądrzejsza słonica.|Słoniątko rodzi się z wagą około stu kilogramów i od razu umie chodzić.',
  rhino: 'Róg nosorożca jest zbudowany z tego samego co nasze paznokcie.|Nosorożec słabo widzi, za to świetnie słyszy i czuje zapachy.|Nosorożce lubią tarzać się w błocie — chroni ono skórę przed słońcem i owadami.|Mimo dużej wagi nosorożec biega szybciej niż człowiek.|Nosorożce jedzą tylko rośliny: trawę, liście i gałązki.|Na grzbiecie nosorożca często siedzą ptaszki — wydziobują owady z jego skóry.',
  brown_bear: 'Niedźwiedź brunatny zimą śpi w gawrze i nie je przez kilka miesięcy.|Niedźwiedź brunatny je prawie wszystko: jagody, orzechy, ryby, miód.|Niedźwiadki rodzą się zimą w gawrze — maleńkie jak kocięta.|Niedźwiedź brunatny świetnie wspina się na drzewa i dobrze pływa.|Węch niedźwiedzia jest o wiele lepszy niż węch psa.|' + own('Niedźwiedzie brunatne żyją także w polskich Tatrach i Bieszczadach.'),
  wolf: 'Wilki żyją w watasze — dużej, zgodnej rodzinie.|Wilki wyją, żeby przywołać swoich i powiedzieć obcym: to nasza ziemia.|Wilk jest przodkiem wszystkich psów.|W ciągu nocy wilcza wataha może przebiec dziesiątki kilometrów.|O wilczęta w watasze dbają wszystkie dorosłe wilki.|Wilki słyszą dźwięki z odległości kilku kilometrów.',
  squirrel: 'Wiewiórka robi zapasy na zimę: chowa orzechy i żołędzie.|Wiewiórka często zapomina o swoich kryjówkach — i wyrastają z nich nowe drzewa.|Puszysty ogon pomaga wiewiórce utrzymać równowagę podczas skoków.|Gniazdo wiewiórki jest okrągłe i ciepłe.|Zęby wiewiórki rosną przez całe życie, dlatego ciągle coś gryzie.|Zimą futerko wiewiórki robi się gęstsze i bardziej szare.',
  owl: 'Sowa poluje nocą: świetnie widzi w ciemności.|Sowa lata prawie bezgłośnie dzięki miękkim piórom.|Sowa nie może poruszać oczami, za to obraca głowę daleko do tyłu.|Słuch sowy jest tak czuły, że słyszy mysz pod śniegiem.|W dzień sowa śpi w dziupli albo wśród gęstych gałęzi.|Pisklęta sowy są pokryte białym puchem.',
  deer: 'Poroże jelenia co roku odpada i wyrasta nowe.|Jelonki rodzą się z białymi plamkami — tak trudniej je zauważyć w trawie.|U leśnych jeleni poroże noszą tylko samce.|Jeleń je trawę, liście, korę i żołędzie.|Jesienią jelenie głośno ryczą — słychać to w całym lesie.|Jeleń jest bardzo płochliwy i ucieka wielkimi skokami.',
  boar: 'Dzik ryje ziemię ryjem, szukając korzonków, żołędzi i chrząszczy.|Młode dzika są pasiaste — paski ukrywają je wśród liści.|Dzik jest przodkiem świni domowej.|Dziki lubią kąpać się w błocie, żeby pozbyć się owadów.|Dzik ma ostre kły, którymi się broni.|Dziki dobrze pływają i szybko biegają.',
  sea_turtle: 'Żółw morski może żyć dłużej niż pół wieku.|Żółwie morskie składają jaja na tej samej plaży, na której same się wykluły.|Zamiast łap żółw morski ma płetwy.|Żółw morski przepływa przez ocean tysiące kilometrów.|Małe żółwiki zaraz po wykluciu biegną do morza.|Żółwie morskie żyły już w czasach dinozaurów.',
  orangutan: 'Orangutan prawie całe życie spędza na drzewach.|Nazwa „orangutan” znaczy „leśny człowiek”.|Co wieczór orangutan buduje sobie na drzewie nowe gniazdo z gałęzi.|Ręce orangutana są dłuższe niż nogi — wygodnie się nimi chwytać gałęzi.|Orangutan jest bardzo mądry: używa patyczków jak narzędzi.|Przed deszczem orangutan chowa się pod wielkim liściem jak pod parasolem.',
  crab: 'Krab chodzi bokiem.|Krab ma dziesięć nóg, a dwie z nich to szczypce.|Pancerz kraba nie rośnie, dlatego krab go zrzuca i hoduje nowy.|Krab potrafi odtworzyć utracone szczypce.|Oczy kraba siedzą na słupkach i patrzą w różne strony.|Największy krab na świecie ma rozpiętość nóg prawie czterech metrów.',
  sloth: 'Leniwiec to najpowolniejsze zwierzę na świecie.|Leniwiec śpi, wisząc na gałęzi grzbietem w dół.|W sierści leniwca rosną glony — przez nie jest zielonkawy.|Na ziemię leniwiec schodzi mniej więcej raz w tygodniu.|Leniwiec pływa lepiej, niż chodzi.|Leniwiec je liście i trawi je przez wiele dni.',
  jellyfish: 'Meduza prawie w całości składa się z wody.|Meduza nie ma ani mózgu, ani serca, ani kości.|Meduzy żyły w oceanie jeszcze przed dinozaurami.|Niektóre meduzy świecą w ciemności.|Czułki meduzy parzą, dlatego nie wolno jej dotykać.|Meduza porusza się, ściskając swój dzwon jak parasol.',
  clownfish: 'Błazenek żyje wśród czułków ukwiału, które parzą inne ryby, ale nie jego.|Błazenek jest jaskrawopomarańczowy w białe paski.|Błazenek czyści ukwiał, a ten go chroni.|Błazenki żyją na ciepłych rafach koralowych.|Błazenek nigdy nie odpływa daleko od swojego domu.|Ikry błazenka pilnuje tata.',
  squid: 'Kałamarnica pływa, wypychając wodę — jak mała rakieta.|Kałamarnica ma osiem ramion i dwie długie macki.|W razie niebezpieczeństwa kałamarnica wypuszcza chmurę atramentu.|Kałamarnica potrafi błyskawicznie zmieniać kolor.|Kałamarnica olbrzymia ma oczy wielkości dużego talerza.|Kałamarnica ma trzy serca.',
  mountain_goat: 'Kozica skacze po prawie pionowych skałach i nie spada.|Racice kozicy są czepne jak buty alpinisty.|Gęsta sierść grzeje kozicę na zimnych szczytach.|Koźlęta już dzień po urodzeniu wspinają się po skałach.|Wysoko w górach kozice chowają się przed drapieżnikami.|Kozice jedzą trawę, mech i porosty.',
  eagle: 'Orzeł widzi zdobycz z bardzo dużej wysokości.|Orzeł buduje gniazdo na wysokich skałach i korzysta z niego przez wiele lat.|Rozpiętość skrzydeł orła jest większa niż wzrost dorosłego człowieka.|Orzeł szybuje w powietrzu, prawie nie machając skrzydłami.|Orzeł ma mocne szpony i haczykowaty dziób.|Para orłów zostaje razem na całe życie.',
  mountain_ram: 'Muflon ma wielkie, zakręcone rogi.|Po rogach muflona można poznać jego wiek — jak po słojach drzewa.|Muflony żyją wysoko w górach, gdzie jest mało drapieżników.|Barany sprawdzają, kto jest silniejszy, zderzając się rogami.|Muflon łatwo skacze z kamienia na kamień.|Zimą muflony schodzą niżej, gdzie jest mniej śniegu.',
};

export const ANIMAL_FACTS: Record<string, string[]> = Object.fromEntries(Object.entries(FACTS).map(([id, text]) => [id, text.split('|')]));
