import type { ThemeId, ThemeSpec } from './theme.types';

/**
 * The six launch themes from the PRD "100500 тем" table (§6). Each theme reskins
 * the mascot, collectible artifact, celebration visuals, the solo dream build,
 * and the full colour palette.
 *
 * Only looks are listed here. A theme's words — its name, its mascot, what its
 * treasures are called — are texts of the app like any other and live in the
 * dictionary (`src/locales/app/<lang>/common.json`, `theme.<id>.…`); `localTheme`
 * puts the two together in the language of the screen.
 */
export const THEMES: Record<ThemeId, ThemeSpec> = {
  /**
   * Neutral, gender-balanced DEFAULT skin used before a child picks a world —
   * a galaxy (Milky Way) look. The child's stored theme is `null` until they
   * choose; everything resolves to this.
   */
  galaxy: {
    id: 'galaxy',
    icon: '🌌',
    mascot: { emoji: '🚀', faces: 'right', tilt: 45 },
    goal: { emoji: '🪐' },
    artifact: { emoji: '⭐' },
    timeToken: { emoji: '🔮' },
    celebrationEmojis: ['⭐', '🌟', '✨', '🪐', '🚀', '☄️'],
    pathIcons: ['⭐', '🪐', '☄️', '🌙', '🛸'],
    dreamBuild: { emoji: '🛰️' },
    chest: { closed: '🛸', open: '✨' },
    treasures: [
      { id: 'star', emoji: '⭐' },
      { id: 'planet', emoji: '🪐' },
      { id: 'comet', emoji: '☄️' },
      { id: 'moon', emoji: '🌙' },
      { id: 'rocket', emoji: '🚀' },
      { id: 'satellite', emoji: '🛰️' },
      { id: 'ufo', emoji: '🛸' },
      { id: 'galaxy', emoji: '🌌' },
    ],
    palette: {
      bg1: '#0b1026',
      bg2: '#2b1a52',
      surface: '#18213f',
      surfaceInk: '#e8ecff',
      primary: '#7c6cff',
      primaryInk: '#ffffff',
      accent: '#35d6e8',
      accentInk: '#052c33',
      text: '#e8ecff',
      textSoft: '#aab2db',
      ring: '#8b7cff',
    },
  },
  unicorns: {
    id: 'unicorns',
    icon: '🦄',
    mascot: { emoji: '🦄', faces: 'left' },
    goal: { emoji: '🌈' },
    artifact: { emoji: '💎' },
    timeToken: { emoji: '⏳' },
    celebrationEmojis: ['🌈', '⭐', '✨', '💖', '🦄'],
    pathIcons: ['💎', '🌟', '🧁', '🍬', '🌸'],
    dreamBuild: { emoji: '🏰' },
    chest: { closed: '🎁', open: '✨' },
    treasures: [
      { id: 'crown', emoji: '👑' },
      { id: 'wand', emoji: '🪄' },
      { id: 'rainbow', emoji: '🌈' },
      { id: 'orb', emoji: '🔮' },
      { id: 'stardust', emoji: '🌟' },
      { id: 'ring', emoji: '💍' },
      { id: 'fairy', emoji: '🧚' },
      { id: 'lolly', emoji: '🍭' },
    ],
    palette: {
      bg1: '#fdf2ff',
      bg2: '#ede9fe',
      surface: '#ffffff',
      surfaceInk: '#4c1d95',
      primary: '#a855f7',
      primaryInk: '#ffffff',
      accent: '#f472b6',
      accentInk: '#ffffff',
      text: '#3b0764',
      textSoft: '#7c6a99',
      ring: '#e879f9',
    },
  },
  cars: {
    id: 'cars',
    icon: '🏎️',
    mascot: { emoji: '🏎️', faces: 'left' },
    goal: { emoji: '🏁' },
    artifact: { emoji: '⚙️' },
    timeToken: { emoji: '⏳' },
    celebrationEmojis: ['🏁', '🏆', '⚙️', '🔥', '🏎️'],
    pathIcons: ['⚙️', '🛞', '🔧', '🏁', '🏆'],
    dreamBuild: { emoji: '🏎️' },
    chest: { closed: '🧰', open: '💥' },
    treasures: [
      { id: 'cup', emoji: '🏆' },
      { id: 'flag', emoji: '🏁' },
      { id: 'wrench', emoji: '🔧' },
      { id: 'gear', emoji: '⚙️' },
      { id: 'tire', emoji: '🛞' },
      { id: 'light', emoji: '🚦' },
      { id: 'medal', emoji: '🏅' },
      { id: 'fuel', emoji: '⛽' },
    ],
    palette: {
      bg1: '#fff7ed',
      bg2: '#fee2e2',
      surface: '#ffffff',
      surfaceInk: '#7f1d1d',
      primary: '#ef4444',
      primaryInk: '#ffffff',
      accent: '#f59e0b',
      accentInk: '#1c1917',
      text: '#7c2d12',
      textSoft: '#9a6a4a',
      ring: '#fb923c',
    },
  },
  space: {
    id: 'space',
    icon: '🚀',
    mascot: { emoji: '🤖' },
    goal: { emoji: '🪐' },
    artifact: { emoji: '☄️' },
    timeToken: { emoji: '⏳' },
    celebrationEmojis: ['⭐', '☄️', '🪐', '✨', '🚀'],
    pathIcons: ['⭐', '🪐', '☄️', '🌙', '🛸'],
    dreamBuild: { emoji: '🚀' },
    chest: { closed: '📦', open: '🌟' },
    treasures: [
      { id: 'ufo', emoji: '🛸' },
      { id: 'planet', emoji: '🪐' },
      { id: 'comet', emoji: '☄️' },
      { id: 'alien', emoji: '👽' },
      { id: 'moon', emoji: '🌙' },
      { id: 'satellite', emoji: '🛰️' },
      { id: 'star', emoji: '⭐' },
      { id: 'telescope', emoji: '🔭' },
    ],
    palette: {
      bg1: '#0f172a',
      bg2: '#1e1b4b',
      surface: '#1e293b',
      surfaceInk: '#e0e7ff',
      primary: '#6366f1',
      primaryInk: '#ffffff',
      accent: '#22d3ee',
      accentInk: '#082f49',
      text: '#e2e8f0',
      textSoft: '#94a3b8',
      ring: '#818cf8',
    },
  },
  dinos: {
    id: 'dinos',
    icon: '🦖',
    mascot: { emoji: '🦖', faces: 'left' },
    goal: { emoji: '🌋' },
    artifact: { emoji: '🐚' },
    timeToken: { emoji: '⏳' },
    celebrationEmojis: ['🦖', '🌿', '🦕', '🥚', '🌋'],
    pathIcons: ['🥚', '🦴', '🌿', '🐚', '🌋'],
    dreamBuild: { emoji: '🏝️' },
    chest: { closed: '🥚', open: '🐣' },
    treasures: [
      { id: 'trex', emoji: '🦖' },
      { id: 'diplo', emoji: '🦕' },
      { id: 'bone', emoji: '🦴' },
      { id: 'egg', emoji: '🥚' },
      { id: 'shell', emoji: '🐚' },
      { id: 'volcano', emoji: '🌋' },
      { id: 'fern', emoji: '🌿' },
      { id: 'footprint', emoji: '🦶' },
    ],
    palette: {
      bg1: '#f0fdf4',
      bg2: '#dcfce7',
      surface: '#ffffff',
      surfaceInk: '#14532d',
      primary: '#16a34a',
      primaryInk: '#ffffff',
      accent: '#ca8a04',
      accentInk: '#ffffff',
      text: '#14532d',
      textSoft: '#4d7c5a',
      ring: '#4ade80',
    },
  },
  underwater: {
    id: 'underwater',
    icon: '🌊',
    mascot: { emoji: '🦀' },
    goal: { emoji: '🏴‍☠️' },
    artifact: { emoji: '🫧' },
    timeToken: { emoji: '🔮' },
    celebrationEmojis: ['🫧', '🐠', '🐬', '⭐', '🐚'],
    pathIcons: ['🐚', '🐠', '🪸', '⭐', '🦀'],
    dreamBuild: { emoji: '🚢' },
    chest: { closed: '🦪', open: '🫧' },
    treasures: [
      { id: 'fish', emoji: '🐠' },
      { id: 'dolphin', emoji: '🐬' },
      { id: 'octopus', emoji: '🐙' },
      { id: 'crab', emoji: '🦀' },
      { id: 'shell', emoji: '🐚' },
      { id: 'turtle', emoji: '🐢' },
      { id: 'treasure', emoji: '🏴‍☠️' },
      { id: 'squid', emoji: '🦑' },
    ],
    palette: {
      bg1: '#ecfeff',
      bg2: '#cffafe',
      surface: '#ffffff',
      surfaceInk: '#164e63',
      primary: '#0891b2',
      primaryInk: '#ffffff',
      accent: '#f59e0b',
      accentInk: '#1c1917',
      text: '#164e63',
      textSoft: '#4a8296',
      ring: '#22d3ee',
    },
  },
  forest: {
    id: 'forest',
    icon: '🌿',
    mascot: { emoji: '🦉' },
    goal: { emoji: '🍎' },
    artifact: { emoji: '🍏' },
    timeToken: { emoji: '⏳' },
    celebrationEmojis: ['🍃', '🍂', '🌰', '🍄', '🦉'],
    pathIcons: ['🍎', '🍐', '🍑', '🍒', '🌰'],
    dreamBuild: { emoji: '🏡' },
    chest: { closed: '🧺', open: '🍃' },
    treasures: [
      { id: 'apple', emoji: '🍎' },
      { id: 'mushroom', emoji: '🍄' },
      { id: 'acorn', emoji: '🌰' },
      { id: 'hedgehog', emoji: '🦔' },
      { id: 'owl', emoji: '🦉' },
      { id: 'pear', emoji: '🍐' },
      { id: 'squirrel', emoji: '🐿️' },
      { id: 'sunflower', emoji: '🌻' },
    ],
    palette: {
      bg1: '#f7fee7',
      bg2: '#ecfccb',
      surface: '#ffffff',
      surfaceInk: '#3f6212',
      primary: '#65a30d',
      primaryInk: '#ffffff',
      accent: '#d97706',
      accentInk: '#ffffff',
      text: '#365314',
      textSoft: '#5f7a3a',
      ring: '#a3e635',
    },
  },
  lego: {
    id: 'lego',
    icon: '🧱',
    mascot: { emoji: '👷' },
    goal: { emoji: '🏰' },
    artifact: { emoji: '🧱' },
    timeToken: { emoji: '⏳' },
    celebrationEmojis: ['🧱', '🟥', '🟨', '🟦', '🟩', '🟧'],
    pathIcons: ['🟥', '🟨', '🟦', '🟩', '🟧', '🧱'],
    dreamBuild: { emoji: '🏰' },
    chest: { closed: '📦', open: '🧱' },
    treasures: [
      { id: 'brick', emoji: '🧱' },
      { id: 'red', emoji: '🟥' },
      { id: 'yellow', emoji: '🟨' },
      { id: 'blue', emoji: '🟦' },
      { id: 'green', emoji: '🟩' },
      { id: 'wheel', emoji: '🛞' },
      { id: 'builder', emoji: '👷' },
      { id: 'crane', emoji: '🏗️' },
    ],
    // The classic toy-brick primaries: red, yellow, blue on white.
    palette: {
      bg1: '#ffd500',
      bg2: '#ffb700',
      surface: '#ffffff',
      surfaceInk: '#1b1b1b',
      primary: '#e3000b',
      primaryInk: '#ffffff',
      accent: '#006cb7',
      accentInk: '#ffffff',
      text: '#1b1b1b',
      textSoft: '#4b4b4b',
      ring: '#00a650',
    },
  },
  frozen: {
    id: 'frozen',
    icon: '❄️',
    mascot: { emoji: '⛄' },
    goal: { emoji: '🏰' },
    artifact: { emoji: '❄️' },
    timeToken: { emoji: '🔮' },
    celebrationEmojis: ['❄️', '✨', '💙', '🩵', '⛄'],
    pathIcons: ['❄️', '⛄', '🩵', '💙', '✨'],
    dreamBuild: { emoji: '🏰' },
    chest: { closed: '🧊', open: '❄️' },
    treasures: [
      { id: 'snowflake', emoji: '❄️' },
      { id: 'snowman', emoji: '⛄' },
      { id: 'ice', emoji: '🧊' },
      { id: 'crystal', emoji: '🩵' },
      { id: 'heart', emoji: '💙' },
      { id: 'mountain', emoji: '🏔️' },
      { id: 'deer', emoji: '🦌' },
      { id: 'spark', emoji: '✨' },
    ],
    palette: {
      bg1: '#f0f9ff',
      bg2: '#e0e7ff',
      surface: '#ffffff',
      surfaceInk: '#1e3a8a',
      primary: '#38bdf8',
      primaryInk: '#083344',
      accent: '#a78bfa',
      accentInk: '#ffffff',
      text: '#1e40af',
      textSoft: '#6b84c0',
      ring: '#7dd3fc',
    },
  },
  minecraft: {
    id: 'minecraft',
    icon: '⛏️',
    mascot: { emoji: '🐷' },
    goal: { emoji: '💎' },
    artifact: { emoji: '🟩' },
    timeToken: { emoji: '⏳' },
    celebrationEmojis: ['🟩', '💎', '⛏️', '🟫', '🧨', '🐷'],
    pathIcons: ['🟫', '🪨', '🟩', '🪵', '💎', '🧨'],
    dreamBuild: { emoji: '🏰' },
    chest: { closed: '📦', open: '💎' },
    treasures: [
      { id: 'pickaxe', emoji: '⛏️' },
      { id: 'sword', emoji: '🗡️' },
      { id: 'axe', emoji: '🪓' },
      { id: 'tnt', emoji: '🧨' },
      { id: 'torch', emoji: '🔥' },
      { id: 'apple', emoji: '🍎' },
      { id: 'bed', emoji: '🛏️' },
      { id: 'diamond', emoji: '💎' },
    ],
    // Sky, grass and the grey of the inventory screen.
    palette: {
      bg1: '#8ecbff',
      bg2: '#5fb0f2',
      surface: '#c6c6c6',
      surfaceInk: '#262626',
      primary: '#4f9a2e',
      primaryInk: '#ffffff',
      accent: '#1fb5a7',
      accentInk: '#ffffff',
      text: '#1d2a14',
      textSoft: '#3d4a33',
      ring: '#f2c94c',
    },
  },
};

export const THEME_LIST: ThemeSpec[] = Object.values(THEMES);
/** The neutral fallback skin used when a child hasn't chosen a theme (null). */
export const DEFAULT_THEME_ID: ThemeId = 'galaxy';
